AMREX_HOME ?= ../../../../..

PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

DIM        = 2
#DIM       = 3

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE 
USE_CUDA   = FALSE

USE_EB     = TRUE

BL_NO_FORT = TRUE

USE_SENSEI_INSITU = FALSE

Bpack   := ./Make.package 
Blocs   := . 

include ../Make.Adv
