# Location of AMReX source on Cooley for ATPESC
AMREX_HOME ?= /projects/ATPESC2019/FASTMath/amrex/amrex 

PRECISION  = DOUBLE

DEBUG      = FALSE

DIM        = 2

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE

Bpack   := ./Make.package 
Blocs   := . 

include ../Make.Adv
