AMREX_HOME ?= ../../../../..

PRECISION  = DOUBLE

DEBUG      = FALSE

DIM        = 2

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE

Bpack   := ./Make.package 
Blocs   := . 

include ../Make.Adv
